### ISSUE TITLE
@conda-forge-admin, please add user @rxm7706

### ISSUE THREAD

**Issue by rxm7706** [conda-forge/opentelemetry-instrumentation-flask-feedstock#19]

**Comment by sy-bee** [comment]
Hi @rxm7706 , I'm wondering if you could help with the https://github.com/conda-forge/opentelemetry-instrumentation-flask-feedstock/pull/22 ? Not sure whether you have permissions to modify this yet due to https://github.com/conda-forge/opentelemetry-sdk-feedstock/issues/34 . Thank you!

**Comment by rxm7706** [comment]
Hi @sy-bee - I don't have permissions yet - I have pinged for help.

**Comment by rxm7706** [comment]
@sy-bee versions 0.39b0, 0.40b0, .0.41b0, 0.42b0, 0.43b0 are available now. You should be gtg. 
https://anaconda.org/conda-forge/opentelemetry-instrumentation-flask/files
Thank you @hmaarrfk !

**Comment by sy-bee** [comment]
Thank you so much @rxm7706 and @hmaarrfk !
